#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000

#spring
spring:
  datasource:
    url: jdbc:mysql:///springst?characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/temp/pages/
    suffix: .html
  aop:
    proxy-target-class: false


#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*.xml

#lOG
logging:
  level:
    com.st: DEBUG
    
#Thread rool
async-thread-pool:
  corePoolSize: 5
  maximumPoolSize: 10
  keepAliveTime: 30
         